config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations",
                                   omniauth_callbacks: "users/omniauth_callbacks"}

  root "static_pages#landing_page"

  get "activity", to: "static_pages#activity"
  get "analytics", to: "static_pages#analytics"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "about", to: "static_pages#about"

  get '/sitemap.xml', to: redirect("https://corsego-public.s3.eu-central-1.amazonaws.com/sitemap.xml")

  resources :enrollments do
    get :teaching, on: :collection
    member do
      get :certificate
    end
  end

  resources :tags, only: [:create, :index, :destroy]
  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
    end

    resources :chapters, except: [:index, :show] do
      put :sort
    end

    resources :lessons, except: [:index] do
      resources :comments, except: [:index, :show, :new, :edit, :update]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: "courses/course_wizard"
  end
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]

  # stripe
  post "checkout/create", to: "checkout#create"
  post "webhooks/create", to: "webhooks#create"

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing_page privacy_policy]

  def landing_page
    @courses = Course.published.approved.order(enrollments_count: :desc, created_at: :desc)
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
  end

  def activity
    redirect_to root_path, alert: 'You are not authorized to access this page' unless current_user.has_role?(:admin)
    @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
  end

  def analytics
    redirect_to root_path, alert: 'You are not authorized to access this page' unless current_user.has_role?(:admin)
  end

  def privacy
  end

  def terms
  end

  def about
  end
end

app/views/static_pages/about.html.haml
.container
  .card.shadow
    .card-header
      %h3
        About Us
    .card-body
      %a{:href => "https://corsego.com", :target => "_blank"} Corsego e-learning platform
      is authored by Yaroslav Shmarov.
      %p
      You can learn to build such applications on your own, as well as discover all my reasonings for this architecture in my
      %b Bestseller Udemy Course
      🎥
      %a{:href => "https://www.udemy.com/course/2519558/?referralCode=4721E9D437DEE1734159"} Ruby on Rails 6: Learn 25+ gems and build a Startup MVP 2020
      %p
      Learn to build an e-learning platform step-by-step. 19 hours of video, 18 chapters and 200 lectures.
      %strong 500+ students already enrolled!
      %hr
      %h3 New hot project!

      💾
      %a{:href => "https://saas.corsego.com"} CorsegoSaaS
      \- Ruby on Rails row-based multitenancy SaaS template. Check it out!
      %p
      🎥
      %a{:href => "https://gumroad.com/l/lHKxjT"} Ruby on Rails 6: Learn to Build a B2B SaaS Multitenancy MVP 2020
      \- 🔥 My New Video Course. Build a multitenancy SaaS step-by-step. 13 hours of video, 20 chapters, 160 lectures.

      %hr
        📕
        %a{:href => "https://blog.corsego.com"} My Ruby on Rails blog
      %p
        💬 You can follow me on Twitter
        %a{:href => "https://twitter.com/yaro_the_slav"} @yaro_the_slav

    .card-footer
      Questions?
      %a{:href => "mailto:hello@corsego.com?subject=Corsego%20SaaS%20question"} Contact us
%br

app/views/static_pages/activity.html.haml
- content_for :title do
  Corsego 
  \| 
  Activity

%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p

%ul.list-group.shadow
  - @activities.each do |activity|
    %li.list-group-item
      /= activity.id
      = activity.created_at.strftime('%d/%m/%Y, %H:%M')
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      = activity.trackable_type
      /= activity.trackable_id
      - if activity.trackable_type == "Lesson"
        - if Lesson.where(id: activity.trackable_id).any?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          that was deleted
      - elsif activity.trackable_type == "Comment"
        - if Comment.where(id: activity.trackable_id).any?
          = link_to activity.trackable.content, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          that was deleted
      - elsif activity.trackable_type == "Course"
        - if Course.where(id: activity.trackable_id).any?
          = link_to activity.trackable, activity.trackable
        - else
          that was deleted
      - else
        = link_to activity.trackable, activity.trackable
      = activity.key
      = crud_label(activity.key.match(/\.(.*)/)[1])
      /= activity.key.match(/\.(.*)/)[1]
      /= activity.owner
      by
      - if activity.owner.present?
        = link_to activity.owner, user_path(activity.owner)
        - if activity.parameters.any?
          = activity.parameters
      - else
        a deleted user
%p
!= pagy_bootstrap_nav(@pagy)
%br

app/views/static_pages/analytics.html.haml
- content_for :title do
  Corsego 
  \| 
  Analytics

%h4.text-center
  New users per day
.card.shadow
  .card-body
    /= line_chart @users.group_by_day(:created_at).count
    = line_chart charts_users_per_day_path

%h4.text-center
  New enrollments per day
.card.shadow
  .card-body
    /= column_chart @enrollments.group_by_day(:created_at).count
    = column_chart charts_enrollments_per_day_path

%h4.text-center
  Most enrolled courses

.card.shadow
  .card-body
    /= pie_chart @courses.group(:enrollments_count).count
    /= pie_chart @enrollments.joins(:course).group(:'courses.title').count
    /= bar_chart @enrollments.joins(:course).group(:'courses.title').count
    = bar_chart charts_course_popularity_path

%h4.text-center
  Most paid courses
.card.shadow
  .card-body
    = bar_chart charts_money_makers_path

app/views/static_pages/landing_page.html.haml
- content_for :title do
  Corsego Online Courses

.jumbotron.shadow.parallax
  %h1.text-shadow
    %b Good Ruby on Rails courses
  .p-4
  - if current_user
    .p-3
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-lg', style: 'float: left; width: 200px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-lg{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
    .p-2
  - else
    %h3.text-shadow Join to access all the courses
    .p-2
    = link_to 'Register', new_user_registration_path, class: 'btn btn-custom-purple btn-lg'
    = link_to 'Login', new_user_session_path, class: 'btn btn-custom-purple btn-lg'
    .row.mt-1
    = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-danger btn-lg mr-1' do
      Continue with
      .fab.fa-google
    .row.mt-1
    = link_to user_github_omniauth_authorize_path, method: :post, class: 'btn btn-dark btn-lg mr-1' do
      Continue with
      .fab.fa-github
    .row.mt-1
    = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'btn btn-primary btn-lg mr-1' do
      Continue with
      .fab.fa-facebook

.card-group.shadow
  .card
    .card-body
      %h1
        .fa.fa-graduation-cap
      = pluralize(Course.approved.published.count, 'online courses')
      .row
      %small Explore a variety of fresh topics
  .card
    .card-body
      %h1
        .fa.fa-chalkboard-teacher
      = pluralize(Course.distinct.count(:user_id), 'expert instructors')
      .row
      %small Find the right instructor for you
  .card
    .card-body
      %h1
        .fa.fa-user-graduate
      = pluralize(User.count, 'active learners')
      .row
      %small Join the knowledge sharing community
  .card
    .card-body
      %h1
        .fa.fa-infinity
      Lifetime access
      .row
      %small Learn on your schedule

%p

%h2 
  .fa.fa-tags
  Top Categories
- @popular_tags.each do |tag|
  = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
    .mt-1.btn.btn-info
      = tag.name
      %span.badge.badge-light
        = tag.course_tags_count
%hr

%h2
  .fa.fa-chart-line
  = link_to 'Popular courses', courses_path(courses_search: {s: 'enrollments_count desc'})
.row
  - @courses.each do |course|
    = render 'courses/course_landscape', course: course
    %p

.card-group.shadow
  .card
    .card-body
      %b
        .fa.fa-clock
        Go at your own pace
      %br
      %small
        Enjoy lifetime access to courses whenever you want
  .card
    .card-body
      %b
        .far.fa-check-circle
        Learn from industry experts
      %br
      %small
        Select from top instructors around the world
  .card
    .card-body
      %b
        .far.fa-play-circle
        Find video courses on almost any topic
      %br
      %small
        Build your library for your career and personal growth

app/views/static_pages/privacy.html.haml
.container
  .card.shadow
    .card-header
      %h3
        Privacy Policy
    .card-body
      %p
        Your privacy is important to us. It is Corsego's policy to respect your privacy regarding any information we may collect from you across our website,
        = succeed "," do
          %a{:href => "http://corsego.com"} corsego.com
      %p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
      %p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
      %p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
      %p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
      %p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
      %p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
      %p This policy is effective as of 24 April 2020.
%br

app/views/static_pages/terms.html.haml
.container
  .card.shadow
    .card-header
      %h3
        Terms and Conditions
    .card-body
      Coming soon!
%br