config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations",
                                   omniauth_callbacks: "users/omniauth_callbacks"}

  root "static_pages#landing_page"

  get "activity", to: "static_pages#activity"
  get "analytics", to: "static_pages#analytics"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "about", to: "static_pages#about"

  get '/sitemap.xml', to: redirect("https://corsego-public.s3.eu-central-1.amazonaws.com/sitemap.xml")

  resources :enrollments do
    get :teaching, on: :collection
    member do
      get :certificate
    end
  end

  resources :tags, only: [:create, :index, :destroy]
  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
    end

    resources :chapters, except: [:index, :show] do
      put :sort
    end

    resources :lessons, except: [:index] do
      resources :comments, except: [:index, :show, :new, :edit, :update]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: "courses/course_wizard"
  end
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]

  # stripe
  post "checkout/create", to: "checkout#create"
  post "webhooks/create", to: "webhooks#create"

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable, :invitable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github facebook]

  rolify

  has_many :courses, dependent: :nullify
  has_many :enrollments, dependent: :nullify
  has_many :user_lessons, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :students, through: :courses, source: :enrollments
  has_many :lessons, through: :user_lessons # lessons viewed by the user

  has_many :enrolled_courses, through: :enrollments, source: :course

  after_create do
    # tell admin that new user signed up
    UserMailer.new_user(self).deliver_later

    # create stripe customer
    Stripe::Customer.create(email: email)

    # assign_default_role
    if User.count == 1
      add_role(:admin) if roles.blank?
      add_role(:teacher)
      add_role(:student)
    else
      add_role(:student) if roles.blank?
      add_role(:teacher) # if you want any user to be able to create own courses
    end
  end

  include PublicActivity::Model
  tracked only: %i[create destroy], owner: :itself
  # tracked owner: Proc.new{ |controller, model| controller.current_user } #current_user is set after create, so it gives an error

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )

    user.name = access_token.info.name
    user.image = access_token.info.image
    user.provider = access_token.provider
    user.uid = access_token.uid
    user.token = access_token.credentials.token
    user.expires_at = access_token.credentials.expires_at
    user.expires = access_token.credentials.expires
    user.refresh_token = access_token.credentials.refresh_token
    user.confirmed_at = Time.zone.now # autoconfirm user from omniauth

    user
  end

  def to_s
    email
  end

  def username
    email.split(/@/).first
  end

  extend FriendlyId
  friendly_id :username_or_id, use: :slugged
  def username_or_id
    if email.present?
      username
    else
      id
    end
  end

  validate :must_have_a_role, on: :update

  def online?
    updated_at > 2.minutes.ago
  end

  def buy_course(course)
    enrollments.create(course: course, price: course.price)
  end

  def view_lesson(lesson)
    view = user_lessons.find_or_create_by(lesson: lesson)
    view.increment!(:impressions)
  end

  def bought?(course)
    enrolled_courses.include?(course)
  end

  def viewed?(lesson)
    lessons.include?(lesson)
  end

  # private

  def calculate_course_income
    update_column :course_income, courses.map(&:income).sum
    update_column :balance, (course_income - enrollment_expences)
  end

  def calculate_enrollment_expences
    update_column :enrollment_expences, enrollments.map(&:price).sum
    update_column :balance, (course_income - enrollment_expences)
  end

  private

  def must_have_a_role
    errors.add(:roles, 'must have at least one role') unless roles.any?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      handle_auth 'Google'
    end

    def github
      handle_auth 'Github'
    end

    def facebook
      handle_auth 'Facebook'
    end

    def handle_auth(kind)
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end

    def failure
      redirect_to root_path, alert: 'Failure. Please try again'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.

    private

    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides reCAPTCHA
        set_minimum_password_length
        respond_with_navigational(resource) { render :new }
      end
    end

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy(@q.result(distinct: true).order(created_at: :desc))

    authorize @users
  end

  def show
    @courses_teaching = @user.courses
    @courses_learning = @user.enrollments.includes(:course)
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to root_path, notice: 'User roles were successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end
end

app/views/users/edit.html.haml
- content_for :title do
  Corsego 
  \/
  Edit roles for
  = @user.username

.card.shadow
  .card-header
    Editing roles for
    = @user.email
  .card-body
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: "btn btn-success"
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
- content_for :title do
  Corsego 
  \| 
  All Users

%h3
  .text-center
    Users
    .badge.badge-info
      = @users.count
%p

.form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.submit
  .ml-2
  = link_to 'refresh', users_path
%br
.table-responsive
  %table.table.table-bordered.table-striped.table-sm.table-hover
    %thead
      %tr
        %th id
        %th= sort_link(@q, :email)
        %th= sort_link(@q, :created_at)
        %th= sort_link(@q, :confirmed_at)
        %th Roles
        %th= sort_link(@q, :courses_count)
        %th= sort_link(@q, :enrollments_count)
        %th= sort_link(@q, :comments_count)
        %th= sort_link(@q, :user_lessons_count, "Lessons viewed")
        %th= sort_link(@q, :course_income)
        %th= sort_link(@q, :enrollment_expences)
        %th= sort_link(@q, :balance)
        %th= 'sign_ins'.humanize
        %th= 'current_sign_in'.humanize
        %th= 'last_sign_in'.humanize
        %th= 'current_ip'.humanize
        %th= 'last_ip'.humanize
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td
            - if user.online?
              .text-success.fa.fa-signal
            - else
              .text-danger.fa.fa-signal
            = link_to user.email, user_path(user)
          %td= user.created_at.strftime('%d/%m/%y, %H:%M')
          %td= boolean_label(user.confirmed?)
          %td
            - user.roles.each do |role|
              .badge.badge-info
                = role.name
            - if policy(user).edit?
              = link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-warning btn-block'
          %td= user.courses_count
          %td= user.enrollments_count
          %td= user.comments_count
          %td= user.user_lessons_count
          %td= user.course_income
          %td= user.enrollment_expences
          %td= user.balance
          %td= user.sign_in_count
          %td
            - if user.current_sign_in_at.present?
              = user.current_sign_in_at.strftime('%d/%m/%y, %H:%M')
          %td
            - if user.last_sign_in_at.present?
              = user.last_sign_in_at.strftime('%d/%m/%y - %H:%M')
          %td= user.current_sign_in_ip
          %td= user.last_sign_in_ip
%p
!= pagy_bootstrap_nav(@pagy)

%br

app/views/users/show.html.haml
- content_for :title do
  Corsego 
  \| 
  = @user.username

.row
  .col-md-6

    .card.shadow
      .card-header
        .fa.fa-user
        - if @user.online?
          .text-success.fa.fa-signal
        - else
          .text-danger.fa.fa-signal
        = link_to @user.username, user_path(@user)
      .card-footer
        - if @user == current_user && @user.uid.nil?
          = link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-outline-primary btn-sm' do
            .fab.fa-google
            Sync with Google
          %p
        - if @user.image?
          .row
          = image_tag @user.image, size: '40x40', alt: "#{@user.email}", class: 'rounded-circle'
        .row
        = @user.name
      .card-footer
        Signed up
        = time_ago_in_words(@user.created_at)
        ago
      - if current_user.has_role?(:admin) || @user = current_user
        .card-footer
          %b= 'email'.humanize + ":"
          = @user.email
          .row
          %b= 'sign_in_count'.humanize + ":"
          = @user.sign_in_count
          .row
          %b= 'current_sign_in_at'.humanize + ":"
          = @user.current_sign_in_at
          .row
          %b= 'last_sign_in_at'.humanize + ":"
          = @user.last_sign_in_at
          .row
          %b= 'current_sign_in_ip'.humanize + ":"
          = @user.current_sign_in_ip
          .row
          %b= 'last_sign_in_ip'.humanize + ":"
          = @user.last_sign_in_ip
        .card-footer
          %b= 'stripe_customer_id'.humanize + ":"
          = @user.stripe_customer_id
        .card-footer
          %b= 'course_income'.humanize + ":"
          = @user.course_income
          .row
          %b= 'enrollment_expences'.humanize + ":"
          = @user.enrollment_expences
          .row
          %b= 'balance'.humanize + ":"
          = @user.balance
      .card-footer
        .fa.fa-graduation-cap
        Courses created:
        = @user.courses_count
        .row
        .fa.fa-lock-open
        Enrollments:
        = @user.enrollments_count
        .row
        .fa.fa-comment
        Comments:
        = @user.comments_count
        .row
        .fa.fa-eye
        Lessons viewed:
        = @user.user_lessons_count
        .row
        .fa.fa-user-graduate
        Students:
        = @user.students.count
      .card-footer
        Confirmed email?
        = boolean_label(@user.confirmed?)
      .card-footer
        - @user.roles.each do |role|
          .badge.badge-info
            = role.name
        - if policy(@user).edit?
          = link_to 'Edit roles', edit_user_path(@user), class: 'btn btn-sm btn-warning'

    %p
  .col-md-6
    .card.shadow
      .card-header
        %b Courses: Teaching
      .card-body
        - @courses_teaching.each do |course|
          .row
          = link_to course.title, course_path(course)
    %p
    .card.shadow
      .card-header
        %b Courses: Learning
      .card-body
        - @courses_learning.each do |enrollment|
          .row
          = link_to enrollment.course.title, course_path(enrollment.course)