config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations",
                                   omniauth_callbacks: "users/omniauth_callbacks"}

  root "static_pages#landing_page"

  get "activity", to: "static_pages#activity"
  get "analytics", to: "static_pages#analytics"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "about", to: "static_pages#about"

  get '/sitemap.xml', to: redirect("https://corsego-public.s3.eu-central-1.amazonaws.com/sitemap.xml")

  resources :enrollments do
    get :teaching, on: :collection
    member do
      get :certificate
    end
  end

  resources :tags, only: [:create, :index, :destroy]
  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
    end

    resources :chapters, except: [:index, :show] do
      put :sort
    end

    resources :lessons, except: [:index] do
      resources :comments, except: [:index, :show, :new, :edit, :update]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: "courses/course_wizard"
  end
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]

  # stripe
  post "checkout/create", to: "checkout#create"
  post "webhooks/create", to: "webhooks#create"

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/models/enrollment.rb
# frozen_string_literal: true

class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  # Course.find_each { |course| Course.reset_counters(course.id, :enrollments) }
  belongs_to :user, counter_cache: true
  # User.find_each { |user| User.reset_counters(user.id, :enrollments) }

  validates :user, :course, presence: true

  validates :rating, presence: { if: :review? }
  validates :review, presence: { if: :rating? }

  validates :user_id, uniqueness: { scope: :course_id } # user cant be subscribed to the same course twice
  validates :course_id, uniqueness: { scope: :user_id } # user cant be subscribed to the same course twice

  validate :cant_subscribe_to_own_course # user can't create a subscription if course.user == current_user.id

  scope :pending_review, -> { where(rating: [0, nil, ''], review: [0, nil, '']) }
  scope :reviewed, -> { where.not(review: [0, nil, '']) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }

  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_user }

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    "#{user} #{course}"
  end

  after_save do
    course.update_rating unless rating.nil? || rating.zero?
  end

  after_destroy do
    course.update_rating
  end

  after_create :calculate_balance
  after_destroy :calculate_balance
  def calculate_balance
    course.calculate_income
    user.calculate_enrollment_expences
  end

  protected

  def cant_subscribe_to_own_course
    errors.add(:base, 'You can not subscribe to your own course') if new_record? && user_id.present? && (user_id == course.user_id)
  end
end

app/controllers/enrollments_controller.rb
# frozen_string_literal: true

class EnrollmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:certificate]
  before_action :set_enrollment, only: %i[show edit update destroy certificate]

  def index
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    authorize @enrollments
  end

  def teaching
    @ransack_path = teaching_enrollments_path
    @q = current_user.students.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
               page_size: 'A4',
               template: 'enrollments/certificate.pdf.haml'
      end
    end
  end

  def show
  end

  def edit
    authorize @enrollment
  end

  def create
    @course = Course.friendly.find(params[:course_id])
    if @course.price.positive?
      redirect_to course_path(@course), alert: 'The course is not free...'
    else
      @enrollment = current_user.buy_course(@course)
      EnrollmentMailer.student_enrollment(@enrollment).deliver_later
      EnrollmentMailer.teacher_enrollment(@enrollment).deliver_later
      redirect_to course_path(@course), notice: 'You are enrolled!'
    end
  end

  def update
    authorize @enrollment
    if @enrollment.update(enrollment_params)
      redirect_to @enrollment, notice: 'Enrollment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy
    redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.'
  end

  private

  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    %h5.card-title
      .text-warning.fa.fa-star
      %b= enrollment.rating
    %h6.card-subtitle.mb-2.text-muted
      .fa.fa-user
      = link_to enrollment.user.username, user_path(enrollment.user)
  .card-body
    %p.card-text
    .fa.fa-comment
    %b= enrollment.review
  .card-footer.text-muted
    %p.card-text
    .fa.fa-clock
    Reviewed 
    #{time_ago_in_words(enrollment.updated_at)} ago
    - if policy(enrollment).edit?
      %p.card-text
      = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5, as: :radio_buttons
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/certificate.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion
  
      /%center
      /  %h1 
      /    Certificate of Completion

      %br
      %br
      %br
      %p
      %h3
        This is to certify that the owner of the email address
      %h2
        %u
          = @enrollment.user.email
      %h3
        has successfully completed the course
      %h2
        %u
          = @enrollment.course.title
      %h3
        on the Corsego.com platform
      
      %p

      %br
      %br
      %br
      %b Certificate id: 
      #{@enrollment.slug}
      
      %p
      
      %b Certificate url: 
      #{request.base_url}#{request.original_fullpath}

      %p
      %b Registration date: 
      #{@enrollment.created_at.strftime('%d-%b-%Y')}
      
      %br
      %br
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('logo-bootstrap.png'), height: "30", width: "auto"
          %p
          www.Corsego.com

app/views/enrollments/edit.html.haml
- content_for :title do
  Corsego 
  |
  Review
  = @enrollment.course

= link_to 'Courses', courses_path
|
= link_to course_path(@enrollment.course) do
  .fa.fa-graduation-cap
  = @enrollment.course.title
|
= link_to 'Add Review', edit_enrollment_path(@enrollment)

.card.shadow
  .card-header
    %h3
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  Corsego 
  |
  = controller_name.humanize
  = action_name.humanize

%h3
  .text-center
    .fa.fa-lock-open
    = controller_name.humanize + ":"
    = action_name.humanize
    .badge.badge-info
      = @enrollments.count
%p

= search_form_for @q, url: @ransack_path do |f|
  = f.search_field :user_email_cont, placeholder: 'user email'
  = f.search_field :course_title_cont, placeholder: 'course title'
  = f.search_field :course_user_email_cont, placeholder: 'teacher'
  = f.search_field :price_eq, placeholder: 'price'
  = f.search_field :rating_eq, placeholder: 'rating'
  = f.submit
= link_to 'refresh', @ransack_path

.table-responsive
  %table.table.table-bordered.table-striped.table-sm.table-hover
    %thead
      %tr
        %th ID
        %th
          = sort_link(@q, :user_email, "User")
          /.fa.fa-user
          /User
        %th
          = sort_link(@q, :created_at)
          /.fa.fa-clock
          /.fa.fa-lock-open
          /bought
        %th
          = sort_link(@q, :course_title, "Course")
          /.fa.fa-graduation-cap
          /Course
        %th Teacher
        %th 
          = sort_link(@q, :price)
          /.fa.fa-dollar-sign
          /Price
        %th 
          .text-warning.fa.fa-clock
          = sort_link(@q, :updated_at, 'Reviewed')
          /Reviewed on
        %th 
          .text-warning.fa.fa-star
          = sort_link(@q, :rating)
        %th 
          .text-warning.fa.fa-comment
          Review
        %th Progress
        %th Certificate
        %th
        %th
        %th
  
    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td
            - if enrollment.user.present?
              = link_to enrollment.user.email, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%m/%Y, %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= link_to enrollment.course.user, user_path(enrollment.course.user)
          %td= number_to_currency(enrollment.price)
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%m/%Y, %H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'PDF', certificate_enrollment_path(enrollment, format: :pdf)
          %td= link_to 'See Review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment)
          %td
            - if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
!= pagy_bootstrap_nav(@pagy)
%br

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment