config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations",
                                   omniauth_callbacks: "users/omniauth_callbacks"}

  root "static_pages#landing_page"

  get "activity", to: "static_pages#activity"
  get "analytics", to: "static_pages#analytics"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "about", to: "static_pages#about"

  get '/sitemap.xml', to: redirect("https://corsego-public.s3.eu-central-1.amazonaws.com/sitemap.xml")

  resources :enrollments do
    get :teaching, on: :collection
    member do
      get :certificate
    end
  end

  resources :tags, only: [:create, :index, :destroy]
  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
    end

    resources :chapters, except: [:index, :show] do
      put :sort
    end

    resources :lessons, except: [:index] do
      resources :comments, except: [:index, :show, :new, :edit, :update]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: "courses/course_wizard"
  end
  resources :youtube, only: :show

  resources :users, only: [:index, :edit, :show, :update]

  # stripe
  post "checkout/create", to: "checkout#create"
  post "webhooks/create", to: "webhooks#create"

  namespace :charts do
    get "users_per_day"
    get "enrollments_per_day"
    get "course_popularity"
    get "money_makers"
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/courses/course_wizard_controller.rb
# frozen_string_literal: true

module Courses
  class CourseWizardController < ApplicationController
    include Wicked::Wizard
    before_action :set_progress, only: %i[show update]
    before_action :set_course, only: %i[show update finish_wizard_path]

    steps :about, :targeting, :pricing, :chapters, :publish

    def show
      authorize @course, :edit?
      case step
      when :about
      when :targeting
        @tags = Tag.all
      when :pricing
      when :chapters
        @course.chapters.build unless @course.chapters.any?
      when :publish
      end
      render_wizard
    end

    def update
      authorize @course, :edit?
      case step
      when :about
      when :targeting
        @tags = Tag.all
      when :pricing
      when :chapters
        # unless @course.chapters.any? # chapter title and content validation fires only if this line is present
        #  @course.chapters.build
        # end
      when :publish
      end
      @course.update(course_params)
      render_wizard @course
    end

    def finish_wizard_path
      authorize @course, :edit?
      # courses_path
      course_path(@course)
    end

    private

    def set_progress
      @progress = if wizard_steps.any? && wizard_steps.index(step).present?
                    ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
                  else
                    0
                  end
    end

    def set_course
      @course = Course.friendly.find params[:course_id]
    end

    def course_params
      params.require(:course).permit(
        :title, :avatar, :marketing_description, :description,
        :language, :level,
        :price,
        :published,
        tag_ids: [],
        chapters_attributes: %i[id title _destroy]
      )
    end
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_course, only: %i[show edit update destroy approve analytics]
  before_action :set_tags, only: %i[index learning pending_review teaching unapproved]

  def index
    @ransack_path = courses_path
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
  end

  def learning
    @ransack_path = learning_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: { user: current_user }).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def teaching
    @ransack_path = teaching_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.published.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def show
    authorize @course
    @chapters = @course.chapters.rank(:row_order).includes(:lessons, lessons: [:user_lessons])
    @reviews = @course.enrollments.reviewed
  end

  def analytics
    authorize @course, :analytics? # admin_or_owner
  end

  def approve
    authorize @course, :approve? # admin
    if @course.approved?
      @course.update(approved: false)
    else
      @course.update(approved: true)
    end
    CourseMailer.approved(@course).deliver_later
    redirect_to @course, notice: "Course approval: #{@course.approved}"
  end

  def new
    @course = Course.new
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.marketing_description = 'Marketing Description'
    @course.description = 'Curriculum Description'
    @course.user = current_user

    if @course.save
      redirect_to course_course_wizard_index_path(@course), notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      redirect_to teaching_courses_path, notice: 'Course was successfully destroyed.'
    else
      redirect_to @course, alert: 'Course has enrollments. Can not be destroyed.'
    end
  end

  private

  def set_tags
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
  end

  def set_course
    @course = Course.friendly.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title)
  end
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to course_path(course) do
          "You created this course #{number_to_currency(course.price)}"
        end
      elsif current_user.bought?(course)
        render 'courses/progress', course: course
      elsif course.price.positive?
        button_to number_to_currency(course.price), checkout_create_path, params: { id: course.id }, remote: true, data: { disable_with: 'validating...' }, class: 'btn btn-success'
      else
        form_tag course_enrollments_path(course) do
          submit_tag 'Enroll for free!', data: { disable_with: 'validating...' }, class: 'btn btn-success'
        end
      end
    else
      link_to 'Check price', new_course_enrollment_path(course), class: 'btn btn-success'
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user && user_course.any?
      if user_course.pending_review.any?
        link_to edit_enrollment_path(user_course.first) do
          "<i class='text-warning fa fa-star'></i>".html_safe + ' ' +
            "<i class='text-dark fa fa-question'></i>".html_safe + ' ' \
            'Add a review'
        end
      else
        link_to enrollment_path(user_course.first) do
          "<i class='text-warning fa fa-star'></i>".html_safe + ' ' +
            "<i class='text-success fa fa-check'></i>".html_safe + ' ' \
            'Thanks for reviewing!'
        end
      end
    end
  end

  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user && user_course.any?
      if course.progress(current_user) == 100
        link_to certificate_enrollment_path(user_course.first, format: :pdf) do
          "<i class='text-danger fa fa-file-pdf'></i>".html_safe + ' ' \
            'Certificate of Completion'
        end
      else
        'Certificate available after completion'
      end
    end
  end
end

app/views/courses/_course.html.haml
.card.shadow
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  - if course.avatar.attached?
    .card-img-top
      = link_to course_path(course) do
        = image_tag course.avatar, loading: "lazy", height: "auto", width: "100%"
        /= image_tag course.avatar, height: "200px", width: "100%"
        /= image_tag course.avatar.variant(resize_to_limit: [100, 100])
        /= image_tag course.avatar.variant(resize_to_fill: [320,240]).processed
  .card-footer
    %small= simple_format(course.marketing_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)
      .row
      = certificate_button(course)

  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        %b= course.average_rating
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-tasks
        = course.lessons_count
      .col-md-6
        .text-right
          - if course.user 
            - if course.user.image?
              = image_tag course.user.image, size: '20x20', alt: "#{course.user.email}", class: 'rounded-circle'
            = link_to course.user.username, user_path(course.user)
  - if current_user
    - if policy(course).owner?
      .card-footer
        .text-center
          .btn-group
            = link_to new_course_chapter_path(course, @chapter), class: 'btn btn-sm btn-primary' do
              .fa.fa-plus
              Chapter
            = link_to new_course_lesson_path(course, @lesson), class: 'btn btn-sm btn-primary' do
              .fa.fa-plus
              Lesson
            = link_to course_course_wizard_index_path(course), class: 'btn btn-sm btn-warning' do
              .fa.fa-edit
              Editor
    - if policy(course).admin_or_owner?
      .card-footer
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info' do
          .fa.fa-chart-bar
          Analtycs
      .card-footer
        .custom-control.custom-switch
          - if course.published?
            %input#customSwitch1.custom-control-input{:disabled => "disabled", :checked => "checked", :type => "checkbox"}/
          - else
            %input#customSwitch2.custom-control-input{:disabled => "disabled", :type => "checkbox"}/
          %label.custom-control-label{:for => "Published"} Teacher Published
        .row
        - if policy(course).approve?
          .custom-control.custom-switch
            = link_to approve_course_path(course), method: :patch do
              - if course.approved?
                %input#customSwitch1.custom-control-input{:type => "checkbox", :checked => "checked"}/
              - else
                %input#customSwitch1.custom-control-input{:type => "checkbox"}/
              %label.custom-control-label{:for => "customSwitch1"} Admin Approved
        - else
          .custom-control.custom-switch
            - if course.approved?
              %input#customSwitch1.custom-control-input{:disabled => "disabled", :checked => "checked", :type => "checkbox"}/
            - else
              %input#customSwitch2.custom-control-input{:disabled => "disabled", :type => "checkbox"}/
            %label.custom-control-label{:for => "Published"} Admin Approved
      - if policy(course).destroy?
        .card-footer
          = link_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' do
            .fa.fa-trash
  - if course.tags.any?
    .card-footer
      - course.tags.each do |tag|
        .badge.badge-info
          = tag.name

app/views/courses/_course_landscape.html.haml
.card.shadow
  .card-body
    .row
      .col-md-4
        - if course.avatar.attached?
          = link_to course_path(course) do
            = image_tag course.avatar, loading: "lazy", height: "auto", width: "100%"
      .col-md-5
        %b= link_to course.title, course_path(course)
        %small= simple_format(course.marketing_description)
        .text-warning.fa.fa-star
        %b= course.average_rating
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-tasks
        = course.lessons_count
        %br
        - if course.tags.any?
          - course.tags.each do |tag|
            .badge.badge-info
              = tag.name
        %br
        - if course.user 
          - if course.user.image?
            = image_tag course.user.image, size: '20x20', alt: "#{course.user.email}", class: 'rounded-circle'
          = link_to course.user.username, user_path(course.user)
      .col-md-3
        .text-center
          = enrollment_button(course)
          .row
          = review_button(course)
          .row
          %small= certificate_button(course)

app/views/courses/_progress.html.haml
.progress
  .progress-bar.bg-success{style: "width: #{course.progress(current_user)}%"}= number_to_percentage(course.progress(current_user), precision: 0)

app/views/courses/analytics.html.haml
- content_for :title do
  Corsego 
  |
  = @course.title
  |
  Analtycs

= link_to 'Courses', courses_path
|
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title
|
= link_to analytics_course_path(@course) do
  .fa.fa-chart-bar
  Analtycs

%h4.text-center
  Enrollments per day, quantity
.card
  .card-body
    = line_chart @course.enrollments.group_by_day(:created_at).count

%h4.text-center
  Enrollments per day, revenue
.card
  .card-body
    = line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

%h4.text-center
  Unique user views (how many unique users viewed the lesson)
.card
  .card-body
    = bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

%h4.text-center
  Impressions per lesson (how many times the lesson was opened)
.card
  .card-body
    = bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

app/views/courses/index.html.haml
- content_for :title do
  Corsego 
  \| 
  = controller_name.humanize
  = action_name.humanize

%h3
  .text-center
    .fa.fa-graduation-cap
    = controller_name.humanize + ":"
    = action_name.humanize
    .badge.badge-info
      = @courses.count
%p

.row
  .col-lg-2.order-0.order-lg-1.shadow
    .sticky-top
      = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
        = f.label :title_or_description
        = f.search_field :title_or_marketing_description_cont, placeholder: 'Title', class: 'form-control form-control-sm'
        .row
        = f.label :tag
        = f.select :course_tags_tag_name_cont, @tags, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        = f.label :language
        .row
        = f.select :language_cont, Course.languages, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        = f.label :level
        .row
        = f.select :level_cont, Course.levels, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        = f.label :price
        = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
        = f.label :teacher
        = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
        .row
        = sort_link(@ransack_courses, :price)
        .row
        = sort_link(@ransack_courses, :average_rating, "Top Rated")
        .row
        = sort_link(@ransack_courses, :enrollments_count, "Most Popular")
        .row
        = sort_link(@ransack_courses, :created_at, "Fresh")
        .row
        = f.button :search, class: "btn btn-block btn-primary"
        - if params[:courses_search]
          .row
          = link_to 'unfilter', {controller: controller_name, action: action_name}, class: "btn btn-block btn-secondary mt-1"
      %hr
      .row
      - @tags.each do |tag|
        = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
          .badge.badge-info
            = tag.name
            %span.badge.badge-light
              = tag.course_tags_count
      %p
      %br
  .col-lg-10.order-1.order-lg-1
    .container
      .row
        - @courses.each do |course|
          = render 'courses/course_landscape', course: course
          %p
    != pagy_bootstrap_nav(@pagy)
%br

app/views/courses/new.html.haml
-# frozen_string_literal: true
- content_for :title do
  Corsego 
  \| 
  New course

.card.shadow
  .card-header
    %h3
      .fa.fa-graduation-cap
      New course
  .card-body
    = simple_form_for(@course) do |f|
      - if @course.errors.any?
        .container.text-danger
          - @course.errors.full_messages.each do |msg|
            %li= msg
      .form-inputs
        = f.input :title, input_html: { autocomplete: 'off' }
      .form-actions
        = f.button :submit
  .card-footer
    = link_to 'Cancel', courses_path

app/views/courses/show.html.haml
- content_for :title do
  = @course.title
.row
  .col-lg-8.order-1.order-lg-1
    .card.shadow
      .card-body
        %h3
          .fa.fa-graduation-cap
          = @course.title
        %hr
        .far.fa-bookmark
        = pluralize(@course.chapters_count, 'Chapter')
        .row
        .fa.fa-tasks
        = pluralize(@course.lessons_count, 'Lesson')
        .row
        .far.fa-clock
        Created
        = @course.created_at.strftime("%m/%Y")
        .row
        .far.fa-clock
        Last updated
        = @course.updated_at.strftime("%m/%Y")
        .row
        .fa.fa-globe-africa
        = @course.language
        .row
        .fa.fa-signal
        = @course.level
        .row
        .fa.fa-file-pdf
        Certificate of Completion
        .row
        .far.fa-comment
        Access to Member-Only Q&A
        .row
        .fa.fa-download
        Access to Member-Only Resources
        .row
        .fa.fa-infinity
        Full Lifetime Access & Updates
        %hr
        = @course.description
    %br
    %h4.text-center
      .far.fa-bookmark
      = pluralize(@course.chapters_count, 'chapter')
      .fa.fa-tasks
      = pluralize(@course.lessons_count, 'lesson')
    - if current_user
      - if @course.user == current_user
        .list-group.shadow.chapter-sortable{:style => "cursor: grab;"}
          - @chapters.each do |chapter|
            = content_tag "div", id: "chapter-#{chapter.id}", data: { id: chapter.id, model_name: chapter.class.name.underscore, update_url: course_chapter_sort_path(@course, chapter)} do
              .list-group-item.list-group-item-secondary
                = render 'chapters/chapter', chapter: chapter
                .list-group.lesson-sortable{:style => "cursor: grab; min-height: 10px;"}
                  - chapter.lessons.rank(:row_order).each do |lesson|
                    = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
                      .list-group-item
                        = render 'lessons/lesson', lesson: lesson
      - elsif current_user.has_role?(:admin) || current_user.bought?(@course)
        .list-group.shadow
          - @chapters.each do |chapter|
            .list-group-item.list-group-item-secondary
              = render 'chapters/chapter', chapter: chapter
              .list-group
                - chapter.lessons.rank(:row_order).each do |lesson|
                  .list-group-item
                    = render 'lessons/lesson', lesson: lesson
      - else
        .list-group.shadow
          - @chapters.each do |chapter|
            .list-group-item.list-group-item-secondary
              = render 'chapters/chapter', chapter: chapter
              .list-group
                - chapter.lessons.rank(:row_order).each do |lesson|
                  .list-group-item
                    = render 'lessons/lesson_preview', lesson: lesson
    - else
      .list-group.shadow
        - @chapters.each do |chapter|
          .list-group-item.list-group-item-secondary
            = render 'chapters/chapter', chapter: chapter
            .list-group
              - chapter.lessons.rank(:row_order).each do |lesson|
                .list-group-item
                  = render 'lessons/lesson_preview', lesson: lesson

    - if @reviews.any?
      %br
      %h4
        .far.fa-comment
        = pluralize(@reviews.count, 'review')
      .list-group
        - @reviews.each do |enrollment|
          .list-group-item
            = render 'enrollments/enrollment', enrollment: enrollment
        %p

  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p

/%hr
/%h4 
/  .fa.fa-graduation-cap
/  Related Courses
/.row
/- @course.similiar_courses.each do |course|
/  .col-md-6
/    = render 'courses/course', course: course
/    %p